### PR TITLE
adjust source maps to account for node script wrapping

### LINKED ISSUE #243: Source maps are misaligned
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.12 - 1.0.26
* Platform / OS version: MacOS Mojave 10.14.3
* Node.js version: 8.12.0

I cannot upgrade past 1.0.26: https://github.com/GoogleChromeLabs/ndb/issues/242#issuecomment-469774129

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. download the js and source map from https://macho-degree.surge.sh/
2. start a local server and `ndb node tmp.min.js`
3. mappings are off

**What is the expected result?**

Mappings should work, just like in Chrome. Go to https://macho-degree.surge.sh/ open devtools and see how it should work.

**What happens instead?**

madness

extracted from https://github.com/terser-js/terser/issues/305

### PR DESCRIPTION
**Pull request by Hoten**
Fixes #243.

### CODE REVIEW

File: front_end/ndb/NdbMain.js [hunk 1]
```diff
@@ -385,11 +380,18 @@ SDK.TextSourceMap.load = async function(sourceMapURL, compiledURL) {
...
-    return new SDK.TextSourceMap(compiledURL, sourceMapURL, payload);
+    textSourceMap = new SDK.TextSourceMap(compiledURL, sourceMapURL, payload);
   } catch (e) {
     console.error(e);
     Common.console.warn('DevTools failed to parse SourceMap: ' + sourceMapURL);
     return null;
   }
+
+  if (textSourceMap._baseURL.startsWith('file://'))
+    for (const mapping of textSourceMap.mappings()) mapping.columnNumber += 62;
```
Comment (Hoten) [inline front_end/ndb/NdbMain.js]: ideas on how to something like this? https://github.com/nodejs/node/issues/17396#issuecomment-348285454. NdbMain doesn't run in node, so can't just do it here.

should maybe do something more clever like this: https://cs.chromium.org/chromium/src/third_party/blink/renderer/devtools/front_end/persistence/Persistence.js?type=cs&q=%22._NodePrefix%22&sq=package:chromium&g=0&l=253 .

File: front_end/ndb/NdbMain.js [hunk 2]
```diff
@@ -356,11 +356,6 @@ Ndb.RestartActionDelegate = class {
   }
 };
 
-SDK.DebuggerModel.prototype.scheduleStepIntoAsync = function() {
```
Comment (Hoten) [inline front_end/ndb/NdbMain.js]: this wasn't working anymore.
