### PR TITLE
fix(ndd): ndd total rework + terminal improvements

### LINKED ISSUE #60: Attach from outside (standalone) ndb
Is there a way to leave `ndb` running and have scripts executed with `node --inspect` be picked up by it?
My current workflow is I open a standalone Node inspector from within Chrome, and leave it running. As I run my scripts that debugger attaches to them.

I can't figure out how to get a standalone `ndb` to attach to my script launched with `node --inspect` from an external terminal. Yes I know I can click specific npm scripts but my workflow is more complicated than clicking a script to run. I use commands to automatically launch build scripts when the filesystem changes, like `git ls **/*.ts | entr npm run debug` (which runs `node --inspect`).

### PR DESCRIPTION
**Pull request by ak239**
fix(ndd): ndd rework

Goal: faster and more reliable ndd implementation without chokidar.
- based on ipc, new process publish its informtion to given named pipe,
  it allows to save ~100 ms before connection, provides stricter
  contract that first started process - reported first, removes requirement
  for temporary folder, simplifies life of other 'node detectors' - they
  can send information to given pipe as well.
- uses execFileSync to block inspected process - port detection hack is
  not needed anymore,
- ndd_service treats running process more responsible and should kill them
  at finish more reliably,
- nuked Ndb.ProcessInfo class on frontend side - it is not needed anymore
- profiler captures data only for current process tree - not for all processes,
- repl gets uncaughtException handler - otherwise it is dead on any async uncaught
  exception.

feat(terminal): add how to use another terminal

When started, terminal shows hint how current ndb instance can be
used with any other local terminal.
```

export NODE_OPTIONS='--require ndb/preload.js --inspect=0'
export NODE_PATH='...'
export NDD_IPC='...'
export NDB_VERSION='1.0.52'

```

Fixes #60

### CODE REVIEW

File: lib/preload/ndb/preload.js [hunk 1]
```diff
@@ -5,48 +5,47 @@
...
-    const url = require('url');
-    const parsedInspectorUrl = url.parse(inspectorUrl);
-    parsedInspectorUrl.pathname = '/json';
-    parsedInspectorUrl.protocol = 'http';
-    inspectorUrl = url.format(parsedInspectorUrl);
-    inspectorPort = Number(parsedInspectorUrl.port);
+  let scriptName = '';
+  try {
+    scriptName = require.resolve(process.argv[1]);
+  } catch (e) {
```
Comment (eugeneo) [inline lib/preload/ndb/preload.js]: nit: empty catch block, maybe add a comment?

File: lib/preload/ndb/preload.js [hunk 2]
```diff
@@ -5,48 +5,47 @@
...
+    data: process.env.NDD_DATA,
+    ppid: ppid,
+    id: String(process.pid),
+    inspectorUrl: require('inspector').url(),
+    scriptName: scriptName
+  };
+  const {execFileSync} = require('child_process');
+  const data = JSON.stringify(info);
+  const code = `(${publish.toString()})(${data}, '${process.env.NDD_IPC}')`;
+  execFileSync(process.execPath, ['-e', `eval(Buffer.from('${Buffer.from(code).toString('base64')}', 'base64').toString())`], {
```
Comment (eugeneo) [inline lib/preload/ndb/preload.js]: This code is hard to understand. I wonder if it could be simplified by running this same file and then switching to a different mode based on command flags.

E.g. take a look at example [here](https://nodejs.org/api/worker_threads.html), where the same script is used to start a worker and as a worker itself.

File: services/ndd_service.js [hunk 3]
```diff
@@ -4,155 +4,106 @@
...
-      const ws = new WebSocket(inspectorUrl);
-      ws.once('open', () => {
-        this._sockets.set(id, ws);
-        this._frontend.detected(id, info);
-      });
-      ws.on('message', rawMessage => {
-        const message = JSON.parse(rawMessage);
-        message.sessionId = id;
-        this._frontend.dispatchMessage(message);
+    const localRelative = path.relative(process.cwd(), `${os.tmpdir()}/`);
```
Comment (eugeneo) [inline services/ndd_service.js]: 1. Why do you need relative path here? `path.join(process.platform === 'win32' ? '\\\\.\\pipe\\' : os.tmpdir(), node-ndb.${process.pid}.sock)` should work.
2. Does path.relative require trailing slash? `relative(process.cwd(), os.tmpdir())` seems to work just fine.

File: services/ndd_service.js [hunk 4]
```diff
@@ -4,155 +4,106 @@
...
+    const pipePrefix = process.platform === 'win32' ? '\\\\.\\pipe\\' : localRelative;
+    const pipeName = `node-ndb.${process.pid}.sock`;
+    this._pipe = path.join(pipePrefix, pipeName);
+    const server = net.createServer(socket => {
+      socket.on('data', async d => {
+        await new Promise(resolve => this._runSession(JSON.parse(d.toString()), frontend, resolve));
```
Comment (eugeneo) [inline services/ndd_service.js]: `_runSession` is already async. Why do you need to wrap it?

File: services/ndd_service.js [hunk 5]
```diff
@@ -4,155 +4,106 @@
...
-    } catch (e) {
-    } finally {
-      process.exit(0);
+  async _runSession(info, frontend, resumeTarget) {
+    const ws = new WebSocket(info.inspectorUrl);
+    const openPromise = new Promise(resolve => ws.once('open', () => resolve(DebugState.WS_OPEN)));
+    const errorPromise = new Promise(resolve => ws.once('error', () => resolve(DebugState.WS_ERROR)));
+    const closePromise = new Promise(resolve => ws.once('close', () => resolve(DebugState.WS_CLOSE)));
+    let state = await Promise.race([openPromise, errorPromise, closePromise, this._disconnectPromise]);
+    if (state === DebugState.WS_OPEN) {
```
Comment (eugeneo) [inline services/ndd_service.js]: I think this code can be simplified by using `openPromise.then`

File: services/ndd_service.js [hunk 6]
```diff
@@ -4,155 +4,106 @@
...
-      nodePath += process.platform === 'win32' ? ';' : ':';
-    nodePath += path.join(__dirname, '..', 'lib', 'preload');
-    const env = {
-      NODE_OPTIONS: `--require ndb/preload.js`,
-      NODE_PATH: nodePath,
-      NDD_STORE: this._nddStores[0],
+  env() {
+    return {
+      NODE_OPTIONS: `--require ndb/preload.js --inspect=0`,
+      NODE_PATH: `${process.env.NODE_PATH || ''}${path.delimiter}${path.join(__dirname, '..', 'lib', 'preload')}`,
```
Comment (eugeneo) [inline services/ndd_service.js]: `path.join(process.env.NODE_PATH || '', __dirname, '..', 'lib', 'preload')`

File: front_end/ndb/NdbMain.js [hunk 7]
```diff
@@ -152,34 +138,29 @@ Ndb.ContextMenuProvider = class {
...
-    InspectorFrontendHost.sendMessageToBackend = this._sendMesage.bind(this);
   }
 
   static async create(targetManager) {
-    const service = await Ndb.backend.createService('ndd_service.js');
-    const manager = new Ndb.NodeProcessManager(targetManager, service);
-    await service.init(rpc.handle(manager));
+    const manager = new Ndb.NodeProcessManager(targetManager);
+    const service = await Ndb.backend.createService('ndd_service.js', rpc.handle(manager));
+    manager._service = service;
```
Comment (eugeneo) [inline front_end/ndb/NdbMain.js]: Do you ever not have service when NodeProcessManager is instantiated?

File: lib/preload/ndb/preload.js (hunk 2 above)
Comment (ak239) [reply lib/preload/ndb/preload.js]: done

File: front_end/ndb/NdbMain.js (hunk 7 above)
Comment (ak239) [reply front_end/ndb/NdbMain.js]: No, but I need to pass handle to service and unfortunately two parts of this thing leaves in different worlds.

File: services/ndd_service.js (hunk 6 above)
Comment (ak239) [reply services/ndd_service.js]: path.join works great for paths and adds path.sep as delimeter but it does not work for PATH environment where path.delimeter should be used.

File: services/ndd_service.js (hunk 5 above)
Comment (ak239) [reply services/ndd_service.js]: disconnect might happen in the middle of ws open, I do not need to connect in this case.

File: services/ndd_service.js (hunk 4 above)
Comment (ak239) [reply services/ndd_service.js]: I tried to split it.

File: services/ndd_service.js (hunk 3 above)
Comment (ak239) [reply services/ndd_service.js]: I got this code from node tests, original commit there said that:

> Modified pipePrefix to use relative path on windows, previously tests failed when the full path was 120+ characters

I think it is outdated, so I removed relative.

File: lib/preload/ndb/preload.js (hunk 1 above)
Comment (ak239) [reply lib/preload/ndb/preload.js]: done
